version: '2'
services:
  bind:
    image: sameersbn/bind:latest
    ports:
      - "53:53/udp"
      - "10000:10000"
    volumes:
      - /srv/docker/bind:/data
    restart: always

  client:
    image: ubuntu:14.04
  main:
    build: .
    ports:
      - "1234:80"
  appa:
    image: nginx
    ports:
      - "2222:80"
  appb:
    image: nginx
    ports:
      - "3333:80"
